### ISSUE TITLE
Property value is not working

### ISSUE THREAD

**Issue by rajesh1158** [baderahmed/react-native-customisable-switch#1]
The default react native switch component has a property named 'value'. Whenever the boolean value of that property is changed, the UI reflects it by on/off. But this component (customisable switch) does not seem to support the property 'value' and setting the state in the 'value' property does not reflect in the UI.

**Comment by jwaltonmedia** [comment]
This looks like an issue with the constructor. `value` is being stored in state as a reference to `props.defaultValue`. But then, when setting `transformValue, backgroundColor, buttonBackgroundColor`, the code is looking for a `value` prop. Changing the ternary expressions to look at the value of `defaultValue` fixes it.

Like so:
```
this.state = {
  value: props.defaultValue,
  transformValue: new Animated.Value(props.defaultValue ? this.transformValue : this.padding),
  backgroundColor: new Animated.Value(props.defaultValue ? 90 : -90),
  buttonBackgroundColor: new Animated.Value(props.defaultValue ? 90 : -90)
};
```

**Comment by rajesh1158** [comment]
This works. Thanks.
