### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by malnikuma** [baderahmed/react-native-customisable-switch#22]
import Switch from 'react-native-customisable-switch';

<Switch
            value={switchOneValue}
            onChangeValue={() => this.setState({ switchOneValue: !switchOneValue })}
          />

Undefined is not an object(evaluating '_react.default.PropTypes.bool')

**Comment by malnikuma** [comment]
yarn add prop-types

import PropTypes from 'prop-types';

replace React.PropTypes with PropTypes

**Comment by ZeeshanAhmadKhalil** [comment]
where is `React.PropTypes` ?
