### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.bool')

### ISSUE THREAD

**Issue by AvijitDutta95** [baderahmed/react-native-customisable-switch#9]
Description

Installed react-native-customisable-switch
Imported it into my screen with` import Switch from 'react-native-customisable-switch';`
Got this error: 
![screenshot_2017-11-09-15-18-12-31](https://user-images.githubusercontent.com/26165120/32599037-50490f38-c561-11e7-96dd-a628e95c139f.png)

version:
```
"react-native-customisable-switch": "^0.1.0",
"react-native": "0.49.3",
"react": "^16.0.0-beta.5",
```

Here is my code for switch design: 

```
<Switch
            value={false}
            onChangeValue={(val) => Alert.alert(val) }
            activeText={'sq mt'}
            inactiveText={'sq ft'}
            fontSize={14}
            activeTextColor={'#1c252a'}
            inactiveTextColor={'#1c252a'}
            switchWidth={77}
            switchHeight={35.5}
            switchBorderRadius={30}
            switchBorderColor={'#dfdfdf'}
            switchBorderWidth={1.5}
            buttonWidth={28}
            buttonHeight={28}
            buttonBorderRadius={100}
            buttonBorderColor={'#456f9b'}
            buttonBorderWidth={1.5}
            animationTime={150}
            padding={true}
            activeBackgroundColor={'#ffffff'}
            inactiveBackgroundColor={'#ffffff'}
            activeButtonBackgroundColor={'#9cc6f1'}
            inactiveButtonBackgroundColor={'#9cc6f1'}
          />
```

And one more thing when i was installed this package with `npm install --save react-native-customisable-switch` on that time old code of your package has been installed on my node_modules folder. 

![capture4](https://user-images.githubusercontent.com/26165120/32599793-987032bc-c563-11e7-9bfb-77e406467403.PNG)

**Comment by antongorodezkiy** [comment]
I have the same issue for the current commit https://github.com/baderahmed/react-native-customisable-switch/commit/5f06710a707dea164eb4dde40a52228246f28b29

---

Thanks to @allantorres92 the issue fixed in PR https://github.com/baderahmed/react-native-customisable-switch/pull/11
